In [1]:
import os
path = '~/Dropbox/projects/richmond/'
os.chdir(os.path.expanduser(path))

In [2]:
import cPickle as pickle
#import richmond
#feats, labels, fines = richmond.loadEx()
#pickle.dump((feats, labels, fines), open( "/tmp/ex.pickle", "wb" ) )

feats, labels, fines = pickle.load(open(os.path.expanduser('~/tmp/ex.pickle')))

In [3]:
from sklearn.cross_validation import train_test_split
feats_pool, feats_val, label_pool, label_val = \
    train_test_split(feats, fines, test_size=0.8, random_state=42)
from hybrid_learner import *

In [5]:
import random, math
l = 1.0
e = 0.1
ratio_p = 0.5
cost_r = 5
budget_t = 50
target_prev = 0
exp = [[], [], feats_val, feats_pool, [], [], label_val, label_pool]
for i in range(100):
    if random.random()>ratio_p:
        heads = True
    else:
        heads = False
    if heads:
        exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.01, step_size=budget_t)
    else:
        exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.99, step_size=budget_t/cost_r)

    target = obj['pr']
    if i == 0:
        target_prev = target

    print 'UPDATE', ratio_p, heads, target, target_prev
    if heads:
        ratio_p = min(ratio_p*l*math.exp(target-target_prev), 1 - e)
    else:
        ratio_p = max(1-(1-ratio_p)*l*math.exp(target-target_prev), e)
    target_prev = target
    exp = exp2
    sys.stdout.flush()

= Experiment on [hybrid_active_396_4]  <- 396 4 14380 59120
[ 7133 10146  7893 11009  7148  2825  8563  6792  3333]

 9
[1950] 1
UPDATE

 0.5 False 0.261942983212 0.261942983212


{
 "active": true, 
 "coarse": false, 
 "pr": 0.26194298321191578, 
 "ratio": 0.99, 
 "roc": 0.9366194490403188, 
 "size": 400
}
{
 "active": true, 
 "coarse": false, 
 "pr": 0.30013157450363892, 
 "ratio": 0.01, 
 "roc": 0.93710516251134901, 
 "size": 410
}

= Experiment on [hybrid_active_405_5]  <- 405 5 14370 59120
[]

 0
[10712, 9070, 7183, 8099, 12252, 11035, 2694, 8464, 3396, 13886, 8669, 10768, 9779, 6936, 13109, 11985, 6171, 4493, 6631, 1795, 14322, 6814, 12896, 2061, 12155, 8496, 3709, 13877, 7001, 11345, 11199, 10671, 2112, 3893, 13896, 314, 7025, 5579, 6502, 10579, 6499, 2307, 13055, 1461, 5630, 6756, 2110, 8396, 8541, 4450] 50
UPDATE

 0.5 True 0.300131574504 0.261942983212



{
 "active": true, 
 "coarse": false, 
 "pr": 0.31679313261190101, 
 "ratio": 0.99, 
 "roc": 0.94015659701098064, 
 "size": 460
}

= Experiment on [hybrid_active_405_55]  <- 405 55 14320 59120
[13937  7798 13003  9488 12201  3621  3353  1882  1453]

 9
[9505] 1
UPDATE

 0.519463573508 False 0.316793132612 0.300131574504



{
 "active": true, 
 "coarse": false, 
 "pr": 0.31528551850814912, 
 "ratio": 0.99, 
 "roc": 0.94106512482743376, 
 "size": 470
}

= Experiment on [hybrid_active_414_56]  <- 414 56 14310 59120


KeyboardInterrupt: 

In [6]:
import random, math
l = 1.0
e = 0.1
ratio_p = 0.5
cost_r = 5
budget_t = 50
target_prev = 0
exp = [[], [], feats_val, feats_pool, [], [], label_val, label_pool]

In [7]:
i=0
heads = True
if heads:
    exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.01, step_size=budget_t)
else:
    exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.99, step_size=budget_t/cost_r)

target = obj['pr']
if i == 0:
    target_prev = target

print 'UPDATE', ratio_p, heads, target, target_prev
if heads:
    ratio_p = min(ratio_p*l*math.exp(target-target_prev), 1 - e)
else:
    ratio_p = max(1-(1-ratio_p)*l*math.exp(target-target_prev), e)
target_prev = target
exp = exp2

= Experiment on [hybrid_active_4_396]  <- 4 396 14380 59120
[ 1950  6943  8048 ...,  8044  3456 12536]

 14380
[] 0
UPDATE 0.5 True 0.244358634231 0.244358634231


{
 "active": true, 
 "coarse": false, 
 "pr": 0.24435863423084495, 
 "ratio": 0.01, 
 "roc": 0.93904521785369721, 
 "size": 400
}


In [9]:
i=1
if random.random()>ratio_p:
    heads = True
else:
    heads = False
if heads:
    exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.01, step_size=budget_t)
else:
    exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.99, step_size=budget_t/cost_r)

target = obj['pr']
if i == 0:
    target_prev = target

print 'UPDATE', ratio_p, heads, target, target_prev
if heads:
    ratio_p = min(ratio_p*l*math.exp(target-target_prev), 1 - e)
else:
    ratio_p = max(1-(1-ratio_p)*l*math.exp(target-target_prev), e)
target_prev = target
exp = exp2

= Experiment on [hybrid_active_405_5]  <- 405 5 14370 59120
UPDATE

 0.5 True 0.300131574504 0.261942983212


{
 "active": true, 
 "coarse": false, 
 "pr": 0.30013157450363892, 
 "ratio": 0.01, 
 "roc": 0.93710516251134901, 
 "size": 410
}


In [10]:
i=2
if random.random()>ratio_p:
    heads = True
else:
    heads = False
if heads:
    exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.01, step_size=budget_t)
else:
    exp2, obj = hybrid_learner(exp, active=True, initial_size=400, fine_ratio=0.99, step_size=budget_t/cost_r)

target = obj['pr']
if i == 0:
    target_prev = target

print 'UPDATE', ratio_p, heads, target, target_prev
if heads:
    ratio_p = min(ratio_p*l*math.exp(target-target_prev), 1 - e)
else:
    ratio_p = max(1-(1-ratio_p)*l*math.exp(target-target_prev), e)
target_prev = target
exp = exp2

= Experiment on [hybrid_active_14775_5]  <- 14775 5 0 59120


KeyboardInterrupt: 

In [20]:
import numpy
a = numpy.array([1,2,3,4,5,6])
a.argsort()[::-1][:1]


array([5])

In [11]:
feats, labels, fines = pickle.load(open(os.path.expanduser('~/tmp/ex.pickle'), 'rb'))